INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'Africa');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Samuel', 'Aldana', 'noobsammy@gmail.com', 3, '2024-08-24');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Julian', 'Arevalo', 'fouhask@gmail.com', 3, '2024-08-24');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Alberto', 'Padilla', 'otaku@gmail.com', 3, '2024-08-24');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Alfredo', 'Alderete', 'osoceloso@gmail.com', 3, '2024-08-24');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Arturo', 'Fuentes', 'peckas@gmail.com', 3, '2024-08-24');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Laura', 'Gómez', 'laura.gomez@example.com', 1, '2024-08-25');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Carlos', 'Mendoza', 'carlos.mendoza@example.com', 1, '2024-08-26');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Sofía', 'Ramírez', 'sofia.ramirez@example.com', 1, '2024-08-27');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Javier', 'Pérez', 'javier.perez@example.com', 1, '2024-08-28');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Ana', 'Martínez', 'ana.martinez@example.com', 1, '2024-08-29');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Miguel', 'Sánchez', 'miguel.sanchez@example.com', 1, '2024-08-30');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Isabel', 'Cruz', 'isabel.cruz@example.com', 2, '2024-08-31');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Ana', 'García', 'ana.garcia@example.com', 2, '2024-08-25');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Luis', 'Martínez', 'luis.martinez@example.com', 2, '2024-08-25');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Marta', 'Fernández', 'marta.fernandez@example.com', 2, '2024-08-25');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('José', 'Pérez', 'jose.perez@example.com', 2, '2024-08-26');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Sofía', 'López', 'sofia.lopez@example.com', 2, '2024-08-26');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Raúl', 'González', 'raul.gonzalez@example.com', 4, '2024-08-26');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Lucía', 'Hernández', 'lucia.hernandez@example.com', 4, '2024-08-27');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Pablo', 'Sánchez', 'pablo.sanchez@example.com', 4, '2024-08-27');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Carmen', 'Ramírez', 'carmen.ramirez@example.com', 4, '2024-08-27');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Juan', 'Torres', 'juan.torres@example.com', 4, '2024-08-28');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Isabel', 'Morales', 'isabel.morales@example.com', 4, '2024-08-28');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Fernando', 'Jiménez', 'fernando.jimenez@example.com', 5, '2024-08-28');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Patricia', 'Vásquez', 'patricia.vasquez@example.com', 5, '2024-08-29');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Carlos', 'Ortega', 'carlos.ortega@example.com', 5, '2024-08-29');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Elena', 'Castro', 'elena.castro@example.com', 5, '2024-08-29');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Andrés', 'Cruz', 'andres.cruz@example.com', 5, '2024-08-30');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Laura', 'Salazar', 'laura.salazar@example.com', 5, '2024-08-30');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Ricardo', 'Suárez', 'ricardo.suarez@example.com', 6, '2024-08-30');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Adriana', 'Paredes', 'adriana.paredes@example.com', 6, '2024-08-31');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Jorge', 'Quintero', 'jorge.quintero@example.com', 6, '2024-08-31');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Mónica', 'Mendoza', 'monica.mendoza@example.com', 6, '2024-08-31');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Óscar', 'Mora', 'oscar.mora@example.com', 6, '2024-09-01');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Natalia', 'Peña', 'natalia.pena@example.com', 6, '2024-09-01');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Héctor', 'Núñez', 'hector.nunez@example.com', 6, '2024-09-01');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Santiago', 'Barrios', 'santiago.barrios@example.com', 7, '2024-09-02');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Valentina', 'Gómez', 'valentina.gomez@example.com', 7, '2024-09-02');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Ricardo', 'Castillo', 'ricardo.castillo@example.com', 7, '2024-09-02');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Diana', 'Lozano', 'diana.lozano@example.com', 7, '2024-09-03');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Felipe', 'Jaramillo', 'felipe.jaramillo@example.com', 7, '2024-09-03');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Carolina', 'Rojas', 'carolina.rojas@example.com', 7, '2024-09-03');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Julián', 'Rivas', 'julian.rivas@example.com', 7, '2024-09-04');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Mariana', 'Peña', 'mariana.pena@example.com', 8, '2024-09-04');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Luis', 'Arango', 'luis.arango@example.com', 8, '2024-09-04');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Ana', 'Mendoza', 'ana.mendoza@example.com', 8, '2024-09-05');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Mauricio', 'Vélez', 'mauricio.velez@example.com', 8, '2024-09-05');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Claudia', 'Arias', 'claudia.arias@example.com', 8, '2024-09-05');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Julian', 'Cuellar', 'julian.cueller@example.com', 8, '2024-09-06');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Sandra', 'Serrano', 'sandra.serrano@example.com', 1, '2024-09-06');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Esteban', 'Salazar', 'esteban.salazar@example.com', 2, '2024-09-06');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Lina', 'Rincón', 'lina.rincon@example.com', 3, '2024-09-07');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('David', 'Martínez', 'david.martinez@example.com', 4, '2024-09-07');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Luisa', 'Calle', 'luisa.calle@example.com', 5, '2024-09-07');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Cristina', 'López', 'cristina.lopez@example.com', 6, '2024-09-08');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Javier', 'Reyes', 'javier.reyes@example.com', 7, '2024-09-08');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Verónica', 'Mora', 'veronica.mora@example.com', 8, '2024-09-08');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Nicolás', 'Castro', 'nicolas.castro@example.com', 1, '2024-09-09');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Gabriela', 'Pardo', 'gabriela.pardo@example.com', 2, '2024-09-09');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES ('Santiago', 'Zapata', 'santiago.zapata@example.com', 3, '2024-09-09');
